# keypoint_dict.py

coco_keypoints = {
    0: 'nose',
    1: 'left_eye',
    2: 'right_eye',
    3: 'left_ear',
    4: 'right_ear',
    5: 'left_shoulder',
    6: 'right_shoulder',
    7: 'left_elbow',
    8: 'right_elbow',
    9: 'left_wrist',
    10: 'right_wrist',
    11: 'left_hip',
    12: 'right_hip',
    13: 'left_knee',
    14: 'right_knee',
    15: 'left_ankle',
    16: 'right_ankle'
}


coco_skeleton = [
    ('nose', 'left_eye'), ('nose', 'right_eye'), ('left_eye', 'left_ear'), ('right_eye', 'right_ear'),
    ('left_shoulder', 'right_shoulder'), ('left_shoulder', 'left_elbow'), ('right_shoulder', 'right_elbow'),
    ('left_elbow', 'left_wrist'), ('right_elbow', 'right_wrist'), ('left_shoulder', 'left_hip'),
    ('right_shoulder', 'right_hip'), ('left_hip', 'right_hip'), ('left_hip', 'left_knee'),
    ('right_hip', 'right_knee'), ('left_knee', 'left_ankle'), ('right_knee', 'right_ankle')
]

alphapose_keypoints = {
    0: 'nose',
    1: 'left_eye',
    2: 'right_eye',
    3: 'left_ear',
    4: 'right_ear',
    5: 'left_shoulder',
    6: 'right_shoulder',
    7: 'left_elbow',
    8: 'right_elbow',
    9: 'left_wrist',
    10: 'right_wrist',
    11: 'left_hip',
    12: 'right_hip',
    13: 'left_knee',
    14: 'right_knee',
    15: 'left_ankle',
    16: 'right_ankle',
    17: 'head_top',
    18: 'neck',
    19: 'pelvis',
    20: 'left_big_toe',  
    21: 'right_big_toe',   
    22: 'left_small_toe',
    23: 'right_small_toe',
    24: 'left_heel',
    25: 'right_heel'
}


alphapose_skeleton = [
    ('left_shoulder', 'right_shoulder'), ('left_shoulder', 'left_elbow'), ('right_shoulder', 'right_elbow'),
    ('left_elbow', 'left_wrist'), ('right_elbow', 'right_wrist'), 
    ('left_hip', 'right_hip'), ('left_hip', 'left_knee'),
    ('right_hip', 'right_knee'), ('left_knee', 'left_ankle'), ('right_knee', 'right_ankle'),
    ('neck', 'head_top'), ('neck', 'pelvis'), ('left_ankle', 'left_big_toe'), ('right_ankle', 'right_big_toe'),
    ('left_ankle', 'left_small_toe'), ('right_ankle', 'right_small_toe'), ('left_ankle', 'left_heel'),
    ('right_ankle', 'right_heel')
]

mediapipe_keypoints = {
    0: 'nose',
    1: 'left_eye_inner',
    2: 'left_eye',
    3: 'left_eye_outer',
    4: 'right_eye_inner',
    5: 'right_eye',
    6: 'right_eye_outer',
    7: 'left_ear',
    8: 'right_ear',
    9: 'mouth_left',
    10: 'mouth_right',
    11: 'left_shoulder',
    12: 'right_shoulder',
    13: 'left_elbow',
    14: 'right_elbow',
    15: 'left_wrist',
    16: 'right_wrist',
    17: 'left_pinky',
    18: 'right_pinky',
    19: 'left_index',
    20: 'right_index',
    21: 'left_thumb',
    22: 'right_thumb',
    23: 'left_hip',
    24: 'right_hip',
    25: 'left_knee',
    26: 'right_knee',
    27: 'left_ankle',
    28: 'right_ankle',
    29: 'left_heel',
    30: 'right_heel',
    31: 'left_foot_index',
    32: 'right_foot_index'
}


mediapipe_skeleton = [
    ('nose', 'left_eye_inner'), ('left_eye_inner', 'left_eye'), ('left_eye', 'left_eye_outer'),
    ('nose', 'right_eye_inner'), ('right_eye_inner', 'right_eye'), ('right_eye', 'right_eye_outer'),
    ('nose', 'left_ear'), ('nose', 'right_ear'), ('left_shoulder', 'right_shoulder'),
    ('left_shoulder', 'left_elbow'), ('right_shoulder', 'right_elbow'), ('left_elbow', 'left_wrist'),
    ('right_elbow', 'right_wrist'), ('left_wrist', 'left_pinky'), ('right_wrist', 'right_pinky'),
    ('left_wrist', 'left_index'), ('right_wrist', 'right_index'), ('left_wrist', 'left_thumb'),
    ('right_wrist', 'right_thumb'), ('left_hip', 'right_hip'), ('left_hip', 'left_knee'),
    ('right_hip', 'right_knee'), ('left_knee', 'left_ankle'), ('right_knee', 'right_ankle'),
    ('left_ankle', 'left_heel'), ('right_ankle', 'right_heel'), ('left_heel', 'left_foot_index'),
    ('right_heel', 'right_foot_index')
]

openpose_keypoints = {
    0: 'nose',
    1: 'neck',
    2: 'right_shoulder',
    3: 'right_elbow',
    4: 'right_wrist',
    5: 'left_shoulder',
    6: 'left_elbow',
    7: 'left_wrist',
    8: 'mid_hip',
    9: 'right_hip',
    10: 'right_knee',
    11: 'right_ankle',
    12: 'left_hip',
    13: 'left_knee',
    14: 'left_ankle',
    15: 'right_eye',
    16: 'left_eye',
    17: 'right_ear',
    18: 'left_ear',
    19: 'left_big_toe',
    20: 'left_small_toe',
    21: 'left_heel',
    22: 'right_big_toe',
    23: 'right_small_toe',
    24: 'right_heel'
}


openpose_skeleton = [
    ('neck', 'right_shoulder'), ('right_shoulder', 'right_elbow'),
    ('right_elbow', 'right_wrist'), ('neck', 'left_shoulder'), ('left_shoulder', 'left_elbow'),
    ('left_elbow', 'left_wrist'), ('neck', 'mid_hip'), ('mid_hip', 'right_hip'), ('right_hip', 'right_knee'),
    ('right_knee', 'right_ankle'), ('mid_hip', 'left_hip'), ('left_hip', 'left_knee'), ('left_knee', 'left_ankle'),
    ('neck', 'right_eye'), ('right_eye', 'right_ear'), ('neck', 'left_eye'), ('left_eye', 'left_ear'),
    ('left_big_toe', 'left_small_toe'), ('left_small_toe', 'left_heel'),
    ('right_big_toe', 'right_small_toe'), ('right_small_toe', 'right_heel')
]


no_face_keypoints = {
    # Body (0–25)
    0: 'nose',
    1: 'left_eye',
    2: 'right_eye',
    3: 'left_ear',
    4: 'right_ear',
    5: 'left_shoulder',
    6: 'right_shoulder',
    7: 'left_elbow',
    8: 'right_elbow',
    9: 'left_wrist',
    10: 'right_wrist',
    11: 'left_hip',
    12: 'right_hip',
    13: 'left_knee',
    14: 'right_knee',
    15: 'left_ankle',
    16: 'right_ankle',
    17: 'neck',
    18: 'head_top',
    19: 'pelvis',
    20: 'thorax',
    21: 'spine',
    22: 'left_heel',
    23: 'right_heel',
    24: 'left_big_toe',
    25: 'right_big_toe',

    # Left Hand (26–46)
    26: 'l_hand_wrist',
    27: 'l_hand_thumb_cmc',
    28: 'l_hand_thumb_mcp',
    29: 'l_hand_thumb_ip',
    30: 'l_hand_thumb_tip',
    31: 'l_hand_index_mcp',
    32: 'l_hand_index_pip',
    33: 'l_hand_index_dip',
    34: 'l_hand_index_tip',
    35: 'l_hand_middle_mcp',
    36: 'l_hand_middle_pip',
    37: 'l_hand_middle_dip',
    38: 'l_hand_middle_tip',
    39: 'l_hand_ring_mcp',
    40: 'l_hand_ring_pip',
    41: 'l_hand_ring_dip',
    42: 'l_hand_ring_tip',
    43: 'l_hand_pinky_mcp',
    44: 'l_hand_pinky_pip',
    45: 'l_hand_pinky_dip',
    46: 'l_hand_pinky_tip',

    # Right Hand (47–67)
    47: 'r_hand_wrist',
    48: 'r_hand_thumb_cmc',
    49: 'r_hand_thumb_mcp',
    50: 'r_hand_thumb_ip',
    51: 'r_hand_thumb_tip',
    52: 'r_hand_index_mcp',
    53: 'r_hand_index_pip',
    54: 'r_hand_index_dip',
    55: 'r_hand_index_tip',
    56: 'r_hand_middle_mcp',
    57: 'r_hand_middle_pip',
    58: 'r_hand_middle_dip',
    59: 'r_hand_middle_tip',
    60: 'r_hand_ring_mcp',
    61: 'r_hand_ring_pip',
    62: 'r_hand_ring_dip',
    63: 'r_hand_ring_tip',
    64: 'r_hand_pinky_mcp',
    65: 'r_hand_pinky_pip',
    66: 'r_hand_pinky_dip',
    67: 'r_hand_pinky_tip'
}


halpe_fullbody_keypoints = {
    # Body (26 keypoints)
    0: 'nose',
    1: 'left_eye',
    2: 'right_eye',
    3: 'left_ear',
    4: 'right_ear',
    5: 'left_shoulder',
    6: 'right_shoulder',
    7: 'left_elbow',
    8: 'right_elbow',
    9: 'left_wrist',
    10: 'right_wrist',
    11: 'left_hip',
    12: 'right_hip',
    13: 'left_knee',
    14: 'right_knee',
    15: 'left_ankle',
    16: 'right_ankle',
    17: 'neck',
    18: 'head_top',
    19: 'pelvis',
    20: 'thorax',
    21: 'spine',
    22: 'left_heel',
    23: 'right_heel',
    24: 'left_big_toe',
    25: 'right_big_toe',
    
    # Face (68 keypoints, indices 26–93)
    26: 'face_0_jawline_start',
    27: 'face_1',
    28: 'face_2',
    29: 'face_3',
    30: 'face_4',
    31: 'face_5',
    32: 'face_6',
    33: 'face_7',
    34: 'face_8',
    35: 'face_9',
    36: 'face_10',
    37: 'face_11',
    38: 'face_12',
    39: 'face_13',
    40: 'face_14',
    41: 'face_15',
    42: 'face_16_jawline_end',
    43: 'face_17_left_eyebrow_start',
    44: 'face_18',
    45: 'face_19',
    46: 'face_20',
    47: 'face_21_left_eyebrow_end',
    48: 'face_22_right_eyebrow_start',
    49: 'face_23',
    50: 'face_24',
    51: 'face_25',
    52: 'face_26_right_eyebrow_end',
    53: 'face_27_nose_bridge_start',
    54: 'face_28',
    55: 'face_29',
    56: 'face_30',
    57: 'face_31_nose_tip',
    58: 'face_32_nostril_left',
    59: 'face_33_nostril_right',
    60: 'face_34_left_eye_outer_corner',
    61: 'face_35',
    62: 'face_36',
    63: 'face_37',
    64: 'face_38_left_eye_inner_corner',
    65: 'face_39_right_eye_inner_corner',
    66: 'face_40',
    67: 'face_41',
    68: 'face_42',
    69: 'face_43_right_eye_outer_corner',
    70: 'face_44_outer_lip_left',
    71: 'face_45',
    72: 'face_46',
    73: 'face_47_outer_lip_top_center',
    74: 'face_48',
    75: 'face_49_outer_lip_right',
    76: 'face_50_inner_lip_right',
    77: 'face_51',
    78: 'face_52_inner_lip_top_center',
    79: 'face_53',
    80: 'face_54_inner_lip_left',
    81: 'face_55_outer_lip_bottom_left',
    82: 'face_56',
    83: 'face_57_outer_lip_bottom_center',
    84: 'face_58',
    85: 'face_59_outer_lip_bottom_right',
    86: 'face_60_inner_lip_bottom_right',
    87: 'face_61',
    88: 'face_62_inner_lip_bottom_center',
    89: 'face_63',
    90: 'face_64_inner_lip_bottom_left',
    91: 'face_65_inner_mouth_left',
    92: 'face_66_inner_mouth_right',
    93: 'face_67',
    
    # Left Hand (21 keypoints, indices 94–114)
    94: 'left_hand_wrist',
    95: 'left_hand_thumb_cmc',
    96: 'left_hand_thumb_mcp',
    97: 'left_hand_thumb_ip',
    98: 'left_hand_thumb_tip',
    99: 'left_hand_index_mcp',
    100: 'left_hand_index_pip',
    101: 'left_hand_index_dip',
    102: 'left_hand_index_tip',
    103: 'left_hand_middle_mcp',
    104: 'left_hand_middle_pip',
    105: 'left_hand_middle_dip',
    106: 'left_hand_middle_tip',
    107: 'left_hand_ring_mcp',
    108: 'left_hand_ring_pip',
    109: 'left_hand_ring_dip',
    110: 'left_hand_ring_tip',
    111: 'left_hand_pinky_mcp',
    112: 'left_hand_pinky_pip',
    113: 'left_hand_pinky_dip',
    114: 'left_hand_pinky_tip',
    
    # Right Hand (21 keypoints, indices 115–135)
    115: 'right_hand_wrist',
    116: 'right_hand_thumb_cmc',
    117: 'right_hand_thumb_mcp',
    118: 'right_hand_thumb_ip',
    119: 'right_hand_thumb_tip',
    120: 'right_hand_index_mcp',
    121: 'right_hand_index_pip',
    122: 'right_hand_index_dip',
    123: 'right_hand_index_tip',
    124: 'right_hand_middle_mcp',
    125: 'right_hand_middle_pip',
    126: 'right_hand_middle_dip',
    127: 'right_hand_middle_tip',
    128: 'right_hand_ring_mcp',
    129: 'right_hand_ring_pip',
    130: 'right_hand_ring_dip',
    131: 'right_hand_ring_tip',
    132: 'right_hand_pinky_mcp',
    133: 'right_hand_pinky_pip',
    134: 'right_hand_pinky_dip',
    135: 'right_hand_pinky_tip'
}


if __name__ == "__main__":
    # Example print statement
    print("Keypoint dictionary loaded.")